// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:daily_rise/data/models/daily_log.dart';
import 'package:daily_rise/data/models/habit_config.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyLogAdapter());
    registerAdapter(HabitConfigAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyLogAdapter());
    registerAdapter(HabitConfigAdapter());
  }
}
